/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Exprs_types.h"

#include <algorithm>

namespace impala {

int _kTExprNodeTypeValues[] = {
  TExprNodeType::BOOL_LITERAL,
  TExprNodeType::CASE_EXPR,
  TExprNodeType::COMPOUND_PRED,
  TExprNodeType::FLOAT_LITERAL,
  TExprNodeType::INT_LITERAL,
  TExprNodeType::IN_PRED,
  TExprNodeType::IS_NULL_PRED,
  TExprNodeType::LIKE_PRED,
  TExprNodeType::LITERAL_PRED,
  TExprNodeType::NULL_LITERAL,
  TExprNodeType::SLOT_REF,
  TExprNodeType::STRING_LITERAL,
  TExprNodeType::TUPLE_IS_NULL_PRED,
  TExprNodeType::FUNCTION_CALL,
  TExprNodeType::AGGREGATE_EXPR,
  TExprNodeType::DECIMAL_LITERAL
};
const char* _kTExprNodeTypeNames[] = {
  "BOOL_LITERAL",
  "CASE_EXPR",
  "COMPOUND_PRED",
  "FLOAT_LITERAL",
  "INT_LITERAL",
  "IN_PRED",
  "IS_NULL_PRED",
  "LIKE_PRED",
  "LITERAL_PRED",
  "NULL_LITERAL",
  "SLOT_REF",
  "STRING_LITERAL",
  "TUPLE_IS_NULL_PRED",
  "FUNCTION_CALL",
  "AGGREGATE_EXPR",
  "DECIMAL_LITERAL"
};
const std::map<int, const char*> _TExprNodeType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(16, _kTExprNodeTypeValues, _kTExprNodeTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kTExtractFieldValues[] = {
  TExtractField::INVALID_FIELD,
  TExtractField::YEAR,
  TExtractField::MONTH,
  TExtractField::DAY,
  TExtractField::HOUR,
  TExtractField::MINUTE,
  TExtractField::SECOND,
  TExtractField::MILLISECOND,
  TExtractField::EPOCH
};
const char* _kTExtractFieldNames[] = {
  "INVALID_FIELD",
  "YEAR",
  "MONTH",
  "DAY",
  "HOUR",
  "MINUTE",
  "SECOND",
  "MILLISECOND",
  "EPOCH"
};
const std::map<int, const char*> _TExtractField_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(9, _kTExtractFieldValues, _kTExtractFieldNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

const char* TBoolLiteral::ascii_fingerprint = "5892306F7B861249AE8E27C8ED619593";
const uint8_t TBoolLiteral::binary_fingerprint[16] = {0x58,0x92,0x30,0x6F,0x7B,0x86,0x12,0x49,0xAE,0x8E,0x27,0xC8,0xED,0x61,0x95,0x93};

uint32_t TBoolLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TBoolLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TBoolLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TBoolLiteral &a, TBoolLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TCaseExpr::ascii_fingerprint = "403F0C4586060E367DA428DD09C59C9C";
const uint8_t TCaseExpr::binary_fingerprint[16] = {0x40,0x3F,0x0C,0x45,0x86,0x06,0x0E,0x36,0x7D,0xA4,0x28,0xDD,0x09,0xC5,0x9C,0x9C};

uint32_t TCaseExpr::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_has_case_expr = false;
  bool isset_has_else_expr = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->has_case_expr);
          isset_has_case_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->has_else_expr);
          isset_has_else_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_has_case_expr)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_has_else_expr)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TCaseExpr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TCaseExpr");

  ++fcnt;
  xfer += oprot->writeFieldBegin("has_case_expr", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->has_case_expr);
  xfer += oprot->writeFieldEnd();

  ++fcnt;
  xfer += oprot->writeFieldBegin("has_else_expr", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->has_else_expr);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TCaseExpr &a, TCaseExpr &b) {
  using ::std::swap;
  swap(a.has_case_expr, b.has_case_expr);
  swap(a.has_else_expr, b.has_else_expr);
}

const char* TDateLiteral::ascii_fingerprint = "56A59CE7FFAF82BCA8A19FAACDE4FB75";
const uint8_t TDateLiteral::binary_fingerprint[16] = {0x56,0xA5,0x9C,0xE7,0xFF,0xAF,0x82,0xBC,0xA8,0xA1,0x9F,0xAA,0xCD,0xE4,0xFB,0x75};

uint32_t TDateLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TDateLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TDateLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TDateLiteral &a, TDateLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TDecimalLiteral::ascii_fingerprint = "EFB929595D312AC8F305D5A794CFEDA1";
const uint8_t TDecimalLiteral::binary_fingerprint[16] = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

uint32_t TDecimalLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TDecimalLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TDecimalLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeBinary(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TDecimalLiteral &a, TDecimalLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TFloatLiteral::ascii_fingerprint = "66FFB53A2471384C03D9F21F6FACA58F";
const uint8_t TFloatLiteral::binary_fingerprint[16] = {0x66,0xFF,0xB5,0x3A,0x24,0x71,0x38,0x4C,0x03,0xD9,0xF2,0x1F,0x6F,0xAC,0xA5,0x8F};

uint32_t TFloatLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TFloatLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TFloatLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_DOUBLE, 1);
  xfer += oprot->writeDouble(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TFloatLiteral &a, TFloatLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TIntLiteral::ascii_fingerprint = "56A59CE7FFAF82BCA8A19FAACDE4FB75";
const uint8_t TIntLiteral::binary_fingerprint[16] = {0x56,0xA5,0x9C,0xE7,0xFF,0xAF,0x82,0xBC,0xA8,0xA1,0x9F,0xAA,0xCD,0xE4,0xFB,0x75};

uint32_t TIntLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TIntLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TIntLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TIntLiteral &a, TIntLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TInPredicate::ascii_fingerprint = "5892306F7B861249AE8E27C8ED619593";
const uint8_t TInPredicate::binary_fingerprint[16] = {0x58,0x92,0x30,0x6F,0x7B,0x86,0x12,0x49,0xAE,0x8E,0x27,0xC8,0xED,0x61,0x95,0x93};

uint32_t TInPredicate::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_is_not_in = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_not_in);
          isset_is_not_in = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_is_not_in)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TInPredicate::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TInPredicate");

  ++fcnt;
  xfer += oprot->writeFieldBegin("is_not_in", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->is_not_in);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TInPredicate &a, TInPredicate &b) {
  using ::std::swap;
  swap(a.is_not_in, b.is_not_in);
}

const char* TIsNullPredicate::ascii_fingerprint = "5892306F7B861249AE8E27C8ED619593";
const uint8_t TIsNullPredicate::binary_fingerprint[16] = {0x58,0x92,0x30,0x6F,0x7B,0x86,0x12,0x49,0xAE,0x8E,0x27,0xC8,0xED,0x61,0x95,0x93};

uint32_t TIsNullPredicate::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_is_not_null = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_not_null);
          isset_is_not_null = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_is_not_null)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TIsNullPredicate::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TIsNullPredicate");

  ++fcnt;
  xfer += oprot->writeFieldBegin("is_not_null", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->is_not_null);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TIsNullPredicate &a, TIsNullPredicate &b) {
  using ::std::swap;
  swap(a.is_not_null, b.is_not_null);
}

const char* TLiteralPredicate::ascii_fingerprint = "403F0C4586060E367DA428DD09C59C9C";
const uint8_t TLiteralPredicate::binary_fingerprint[16] = {0x40,0x3F,0x0C,0x45,0x86,0x06,0x0E,0x36,0x7D,0xA4,0x28,0xDD,0x09,0xC5,0x9C,0x9C};

uint32_t TLiteralPredicate::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;
  bool isset_is_null = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_null);
          isset_is_null = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_is_null)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TLiteralPredicate::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TLiteralPredicate");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->value);
  xfer += oprot->writeFieldEnd();

  ++fcnt;
  xfer += oprot->writeFieldBegin("is_null", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->is_null);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TLiteralPredicate &a, TLiteralPredicate &b) {
  using ::std::swap;
  swap(a.value, b.value);
  swap(a.is_null, b.is_null);
}

const char* TTupleIsNullPredicate::ascii_fingerprint = "A803C54EAD95E24D90C5E66FB98EA72B";
const uint8_t TTupleIsNullPredicate::binary_fingerprint[16] = {0xA8,0x03,0xC5,0x4E,0xAD,0x95,0xE2,0x4D,0x90,0xC5,0xE6,0x6F,0xB9,0x8E,0xA7,0x2B};

uint32_t TTupleIsNullPredicate::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_tuple_ids = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->tuple_ids.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->tuple_ids.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readI32(this->tuple_ids[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          isset_tuple_ids = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_tuple_ids)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TTupleIsNullPredicate::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TTupleIsNullPredicate");

  ++fcnt;
  xfer += oprot->writeFieldBegin("tuple_ids", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->tuple_ids.size()));
    std::vector< ::impala::TTupleId> ::const_iterator _iter5;
    for (_iter5 = this->tuple_ids.begin(); _iter5 != this->tuple_ids.end(); ++_iter5)
    {
      xfer += oprot->writeI32((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TTupleIsNullPredicate &a, TTupleIsNullPredicate &b) {
  using ::std::swap;
  swap(a.tuple_ids, b.tuple_ids);
}

const char* TSlotRef::ascii_fingerprint = "E86CACEB22240450EDCBEFC3A83970E4";
const uint8_t TSlotRef::binary_fingerprint[16] = {0xE8,0x6C,0xAC,0xEB,0x22,0x24,0x04,0x50,0xED,0xCB,0xEF,0xC3,0xA8,0x39,0x70,0xE4};

uint32_t TSlotRef::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_slot_id = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->slot_id);
          isset_slot_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_slot_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TSlotRef::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TSlotRef");

  ++fcnt;
  xfer += oprot->writeFieldBegin("slot_id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->slot_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TSlotRef &a, TSlotRef &b) {
  using ::std::swap;
  swap(a.slot_id, b.slot_id);
}

const char* TStringLiteral::ascii_fingerprint = "EFB929595D312AC8F305D5A794CFEDA1";
const uint8_t TStringLiteral::binary_fingerprint[16] = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

uint32_t TStringLiteral::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_value = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->value);
          isset_value = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_value)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TStringLiteral::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TStringLiteral");

  ++fcnt;
  xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->value);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TStringLiteral &a, TStringLiteral &b) {
  using ::std::swap;
  swap(a.value, b.value);
}

const char* TAggregateExpr::ascii_fingerprint = "5892306F7B861249AE8E27C8ED619593";
const uint8_t TAggregateExpr::binary_fingerprint[16] = {0x58,0x92,0x30,0x6F,0x7B,0x86,0x12,0x49,0xAE,0x8E,0x27,0xC8,0xED,0x61,0x95,0x93};

uint32_t TAggregateExpr::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_is_merge_agg = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->is_merge_agg);
          isset_is_merge_agg = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_is_merge_agg)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TAggregateExpr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TAggregateExpr");

  ++fcnt;
  xfer += oprot->writeFieldBegin("is_merge_agg", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->is_merge_agg);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TAggregateExpr &a, TAggregateExpr &b) {
  using ::std::swap;
  swap(a.is_merge_agg, b.is_merge_agg);
}

const char* TExprNode::ascii_fingerprint = "33403D37A096279061806859579BCB89";
const uint8_t TExprNode::binary_fingerprint[16] = {0x33,0x40,0x3D,0x37,0xA0,0x96,0x27,0x90,0x61,0x80,0x68,0x59,0x57,0x9B,0xCB,0x89};

uint32_t TExprNode::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_node_type = false;
  bool isset_type = false;
  bool isset_num_children = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast6;
          xfer += iprot->readI32(ecast6);
          this->node_type = (TExprNodeType::type)ecast6;
          isset_node_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->type.read(iprot);
          isset_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->num_children);
          isset_num_children = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->fn.read(iprot);
          this->__isset.fn = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->vararg_start_idx);
          this->__isset.vararg_start_idx = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->bool_literal.read(iprot);
          this->__isset.bool_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->case_expr.read(iprot);
          this->__isset.case_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->date_literal.read(iprot);
          this->__isset.date_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->float_literal.read(iprot);
          this->__isset.float_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->int_literal.read(iprot);
          this->__isset.int_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->in_predicate.read(iprot);
          this->__isset.in_predicate = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->is_null_pred.read(iprot);
          this->__isset.is_null_pred = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->literal_pred.read(iprot);
          this->__isset.literal_pred = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->slot_ref.read(iprot);
          this->__isset.slot_ref = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->string_literal.read(iprot);
          this->__isset.string_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->tuple_is_null_pred.read(iprot);
          this->__isset.tuple_is_null_pred = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 17:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->decimal_literal.read(iprot);
          this->__isset.decimal_literal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 18:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->agg_expr.read(iprot);
          this->__isset.agg_expr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_node_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_num_children)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TExprNode::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TExprNode");

  ++fcnt;
  xfer += oprot->writeFieldBegin("node_type", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->node_type);
  xfer += oprot->writeFieldEnd();

  ++fcnt;
  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->type.write(oprot);
  xfer += oprot->writeFieldEnd();

  ++fcnt;
  xfer += oprot->writeFieldBegin("num_children", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->num_children);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.fn) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("fn", ::apache::thrift::protocol::T_STRUCT, 4);
    xfer += this->fn.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.vararg_start_idx) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("vararg_start_idx", ::apache::thrift::protocol::T_I32, 5);
    xfer += oprot->writeI32(this->vararg_start_idx);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.bool_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("bool_literal", ::apache::thrift::protocol::T_STRUCT, 6);
    xfer += this->bool_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.case_expr) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("case_expr", ::apache::thrift::protocol::T_STRUCT, 7);
    xfer += this->case_expr.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.date_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("date_literal", ::apache::thrift::protocol::T_STRUCT, 8);
    xfer += this->date_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.float_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("float_literal", ::apache::thrift::protocol::T_STRUCT, 9);
    xfer += this->float_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.int_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("int_literal", ::apache::thrift::protocol::T_STRUCT, 10);
    xfer += this->int_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.in_predicate) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("in_predicate", ::apache::thrift::protocol::T_STRUCT, 11);
    xfer += this->in_predicate.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.is_null_pred) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("is_null_pred", ::apache::thrift::protocol::T_STRUCT, 12);
    xfer += this->is_null_pred.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.literal_pred) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("literal_pred", ::apache::thrift::protocol::T_STRUCT, 13);
    xfer += this->literal_pred.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.slot_ref) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("slot_ref", ::apache::thrift::protocol::T_STRUCT, 14);
    xfer += this->slot_ref.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.string_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("string_literal", ::apache::thrift::protocol::T_STRUCT, 15);
    xfer += this->string_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tuple_is_null_pred) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("tuple_is_null_pred", ::apache::thrift::protocol::T_STRUCT, 16);
    xfer += this->tuple_is_null_pred.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.decimal_literal) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("decimal_literal", ::apache::thrift::protocol::T_STRUCT, 17);
    xfer += this->decimal_literal.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.agg_expr) {
    ++fcnt;
    xfer += oprot->writeFieldBegin("agg_expr", ::apache::thrift::protocol::T_STRUCT, 18);
    xfer += this->agg_expr.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TExprNode &a, TExprNode &b) {
  using ::std::swap;
  swap(a.node_type, b.node_type);
  swap(a.type, b.type);
  swap(a.num_children, b.num_children);
  swap(a.fn, b.fn);
  swap(a.vararg_start_idx, b.vararg_start_idx);
  swap(a.bool_literal, b.bool_literal);
  swap(a.case_expr, b.case_expr);
  swap(a.date_literal, b.date_literal);
  swap(a.float_literal, b.float_literal);
  swap(a.int_literal, b.int_literal);
  swap(a.in_predicate, b.in_predicate);
  swap(a.is_null_pred, b.is_null_pred);
  swap(a.literal_pred, b.literal_pred);
  swap(a.slot_ref, b.slot_ref);
  swap(a.string_literal, b.string_literal);
  swap(a.tuple_is_null_pred, b.tuple_is_null_pred);
  swap(a.decimal_literal, b.decimal_literal);
  swap(a.agg_expr, b.agg_expr);
  swap(a.__isset, b.__isset);
}

const char* TExpr::ascii_fingerprint = "01EFF48BB9FFD609F9A86B77FA7F9846";
const uint8_t TExpr::binary_fingerprint[16] = {0x01,0xEF,0xF4,0x8B,0xB9,0xFF,0xD6,0x09,0xF9,0xA8,0x6B,0x77,0xFA,0x7F,0x98,0x46};

uint32_t TExpr::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_nodes = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->nodes.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _etype10;
            xfer += iprot->readListBegin(_etype10, _size7);
            this->nodes.resize(_size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              xfer += this->nodes[_i11].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_nodes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_nodes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TExpr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TExpr");

  ++fcnt;
  xfer += oprot->writeFieldBegin("nodes", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->nodes.size()));
    std::vector<TExprNode> ::const_iterator _iter12;
    for (_iter12 = this->nodes.begin(); _iter12 != this->nodes.end(); ++_iter12)
    {
      xfer += (*_iter12).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TExpr &a, TExpr &b) {
  using ::std::swap;
  swap(a.nodes, b.nodes);
}

const char* TExprBatch::ascii_fingerprint = "E968773DC466D549504A7C681FF8B82E";
const uint8_t TExprBatch::binary_fingerprint[16] = {0xE9,0x68,0x77,0x3D,0xC4,0x66,0xD5,0x49,0x50,0x4A,0x7C,0x68,0x1F,0xF8,0xB8,0x2E};

uint32_t TExprBatch::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_exprs = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->exprs.clear();
            uint32_t _size13;
            ::apache::thrift::protocol::TType _etype16;
            xfer += iprot->readListBegin(_etype16, _size13);
            this->exprs.resize(_size13);
            uint32_t _i17;
            for (_i17 = 0; _i17 < _size13; ++_i17)
            {
              xfer += this->exprs[_i17].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_exprs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_exprs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t TExprBatch::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  uint32_t fcnt = 0;
  xfer += oprot->writeStructBegin("TExprBatch");

  ++fcnt;
  xfer += oprot->writeFieldBegin("exprs", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->exprs.size()));
    std::vector<TExpr> ::const_iterator _iter18;
    for (_iter18 = this->exprs.begin(); _iter18 != this->exprs.end(); ++_iter18)
    {
      xfer += (*_iter18).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TExprBatch &a, TExprBatch &b) {
  using ::std::swap;
  swap(a.exprs, b.exprs);
}

} // namespace
