/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "beeswax_constants.h"

namespace beeswax {

const beeswaxConstants g_beeswax_constants;

beeswaxConstants::beeswaxConstants() {
}

} // namespace

