/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef beeswax_CONSTANTS_H
#define beeswax_CONSTANTS_H

#include "beeswax_types.h"

namespace beeswax {

class beeswaxConstants {
 public:
  beeswaxConstants();

};

extern const beeswaxConstants g_beeswax_constants;

} // namespace

#endif
